image: docker

services:
- docker:dind

before_script:
 - export
 - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com

build:
  script:
    - docker pull registry.gitlab.com/anakin174/flatris:master
    - docker build --cache-from registry.gitlab.com/anakin174/flatris:master --tag registry.gitlab.com/anakin174/flatris:master --tag "registry.gitlab.com/anakin174/flatris:$CI_COMMIT_SHA" .
    - docker push registry.gitlab.com/anakin174/flatris:master
    - docker push "registry.gitlab.com/anakin174/master:$CI_COMMIT_SHA"
